### ISSUE TITLE
global name 'PATTERN_INSTANCES_MAX' is not defined

### ISSUE THREAD

**Issue by cyberixae** [kunquat/kunquat#387]
Traceback (most recent call last):
  File "/home/twruottu/kunquat/lib/python2.7/site-packages/kunquat/tracker/ui/views/orderlisteditor.py", line 235, in _pattern_reused
    instance_num = self._album.get_new_pattern_instance_num(pattern_num)
  File "/home/twruottu/kunquat/lib/python2.7/site-packages/kunquat/tracker/ui/model/album.py", line 105, in get_new_pattern_instance_num
    free_nums = set(xrange(PATTERN_INSTANCES_MAX))
NameError: global name 'PATTERN_INSTANCES_MAX' is not defined

**Comment by cyberixae** [comment]
This seems to happen every time as a result of clicking "Reuse pattern" button.

**Comment by cyberixae** [comment]
twruottu@kunquatkone:~$ python --version
Python 2.7.6
twruottu@kunquatkone:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
