### ISSUE TITLE
Kunquat-player and kunquat-export fail on some locales

### ISSUE THREAD

**Issue by cyberixae** [kunquat/kunquat#585]
Player:
```
cyberix@kunquatkone:~$ LANG=POSIX ~/kunquat/bin/kunquat-player ~/kunquat/share/doc/kunquat/examples/example.kqt.bz2 
Playing /home/cyberix/kunquat/share/doc/kunquat/examples/example.kqt.bz2
Traceback (most recent call last):
  File "/home/cyberix/kunquat/bin/kunquat-player", line 619, in <module>
    main()
  File "/home/cyberix/kunquat/bin/kunquat-player", line 393, in main
    play_all(options, paths)
  File "/home/cyberix/kunquat/bin/kunquat-player", line 291, in play_all
    action = play(options, file_name, pa_handle, key_handler, list_pos)
  File "/home/cyberix/kunquat/bin/kunquat-player", line 169, in play
    print_meta(meta)
  File "/home/cyberix/kunquat/bin/kunquat-player", line 101, in print_meta
    print('\n'.join(rows))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 38: ordinal not in range(128)
```

Export:
```
cyberix@kunquatkone:~$ LANG=POSIX ~/kunquat/bin/kunquat-export ~/kunquat/share/doc/kunquat/examples/example.kqt.bz2 
Exporting /home/cyberix/kunquat/share/doc/kunquat/examples/example.kqt.bz2 to example.wav
Traceback (most recent call last):
  File "/home/cyberix/kunquat/bin/kunquat-export", line 384, in <module>
    main()
  File "/home/cyberix/kunquat/bin/kunquat-export", line 290, in main
    export_all(options, paths)
  File "/home/cyberix/kunquat/bin/kunquat-export", line 137, in export_all
    export(path, out_path, options)
  File "/home/cyberix/kunquat/bin/kunquat-export", line 107, in export
    clen = print_status_line(handle.nanoseconds, duration, clipped)
  File "/home/cyberix/kunquat/bin/kunquat-export", line 146, in print_status_line
    print(line, end='\r')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-14: ordinal not in range(128)
```

**Comment by cyberixae** [comment]
Not sure if we want to support locales but at the moment we do not and I thought it was worth pointing out.

**Comment by cyberixae** [comment]
Perhaps we could print a warning or refuse to run the command line tools if the user is on some weird locale.
