### ISSUE TITLE
Make kunquat-tracker work on macOS

### ISSUE THREAD

**Issue by cyberixae** [kunquat/kunquat#698]
The tracker doesn't seem to work on MacOS at the moment. Not sure why exactly.

**Comment by cyberixae** [comment]
Here are the current macOS installation instructions for the Kunquat command line tools.
```
brew install wget python3 libsndfile wavpack pkg-config check pulseaudio
./get_build_support.sh
./make.py --disable-threads --disable-tests
./make.py --disable-threads --disable-tests --prefix=~/kunquat install
export LD_LIBRARY_PATH=~/kunquat/lib
export PYTHONPATH=`python3 -c "import os, sys; print(os.path.expanduser('~/kunquat/lib/python{0}.{1}/site-packages'.format(*sys.version_info)))"`
~/kunquat/bin/kunquat-player
~/kunquat/bin/kunquat-export
```

**Comment by cyberixae** [comment]
If I run the tracker command `~/kunquat/bin/kunquat-tracker` instead I'll get the following error message.

```
Traceback (most recent call last):
  File "/Users/cyberixae/kunquat/bin/kunquat-tracker", line 4, in <module>
    from kunquat.tracker.tracker import main
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/tracker.py", line 22, in <module>
    from .processes.uiprocess import create_ui_process
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/processes/uiprocess.py", line 18, in <module>
    from kunquat.tracker.ui.uilauncher import create_ui_launcher
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/uilauncher.py", line 22, in <module>
    from kunquat.tracker.ui.qt import *
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/qt.py", line 14, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'
```

**Comment by cyberixae** [comment]
It is quite obvious from the stack trace that PyQt5 is missing, so I decided to install it by running `pip3 install pyqt5`. Now when I run the tracker I get the following error message.
```
Traceback (most recent call last):
  File "/Users/cyberixae/kunquat/bin/kunquat-tracker", line 4, in <module>
    from kunquat.tracker.tracker import main
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/tracker.py", line 22, in <module>
    from .processes.uiprocess import create_ui_process
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/processes/uiprocess.py", line 18, in <module>
    from kunquat.tracker.ui.uilauncher import create_ui_launcher
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/uilauncher.py", line 27, in <module>
    from kunquat.tracker.ui.model.uimodel import create_ui_model
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/model/uimodel.py", line 21, in <module>
    from .module import Module
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/model/module.py", line 21, in <module>
    from .audiounit import AudioUnit
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/model/audiounit.py", line 19, in <module>
    from .processor import Processor
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/model/processor.py", line 30, in <module>
    from .procparams.sampleparams import SampleParams
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/model/procparams/sampleparams.py", line 14, in <module>
    from kunquat.extras.samplerate import SampleRate, SRC_SINC_BEST_QUALITY
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/extras/samplerate.py", line 283, in <module>
    _samplerate.src_strerror.argtypes = [ctypes.c_int]
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, src_strerror): symbol not found
```

**Comment by kagu** [comment]
Do you have libsamplerate installed?

**Comment by cyberixae** [comment]
I did not as it is not part of the current installation instructions. I wonder if this affects the command line tools as well.

**Comment by cyberixae** [comment]
I got it installed now with `brew install libsamplerate`. After this I get a silent crash when attempting to run the tracker. Then macOS debugger opens with a very serious looking stack trace and tells me the following.
```
BUG IN CLIENT OF LIBDISPATCH: Assertion failed: Block was expected to execute on queue [com.apple.main-thread]
crashed on child side of fork pre-exec
```

**Comment by cyberixae** [comment]
Using `multiprocessing.set_start_method('spawn')` the correct spot seems to fix the LIBDISPATCH problem. See https://github.com/kunquat/kunquat/pull/706 After this change i get the following error

```
Traceback (most recent call last):
  File "/Users/cyberixae/src/kunquat/kunquat/tracker/ui/uilauncher.py", line 77, in update
    self._process_event_queue()
  File "/Users/cyberixae/src/kunquat/kunquat/tracker/processes/uiprocess.py", line 164, in _process_queue
    self._q.update()
  File "/Users/cyberixae/src/kunquat/kunquat/tracker/processes/uiprocess.py", line 39, in update
    in_count = self._in.qsize()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```

**Comment by cyberixae** [comment]
We made some experiments by replacing the `qsize()` calls with hard coded value `16384`. After this the macOS debugger opens again with the more serious looking stack trace and tells me the following.
```
BUG IN CLIENT OF LIBDISPATCH: _dispatch_main_queue_callback_4CF called from the wrong thread
crashed on child side of fork pre-exec
```

**Comment by cyberixae** [comment]
The change in pull request https://github.com/kunquat/kunquat/pull/706 does not make sense. I must have failed somehow while I was testing it. Pull request https://github.com/kunquat/kunquat/pull/709 should be a more sensible iteration on the same idea.

**Comment by cyberixae** [comment]
Pull request https://github.com/kunquat/kunquat/pull/711/files adds support for using magic numbers instead of qsize calls when qsize calls throw `NotImplementedError`.

**Comment by cyberixae** [comment]
Kunquat-tracker should now work on Mac to some degree. Pull request https://github.com/kunquat/kunquat/pull/712 updates the installation instructions to match the current status. I'm closing this bug report. Feel free to file new bugs for any remaining problems.
