### ISSUE TITLE
Libkunquat tests do not pass on macOS

### ISSUE THREAD

**Issue by cyberixae** [kunquat/kunquat#714]

**Comment by absolutelynothinghere** [comment]
I'm having this issue on linux, can't compile unless I disable tests. Starting Kunquat afterwards results in:

```
Process Kunquat Tracker UI:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/anon/kunquat/lib/python3.9/site-packages/kunquat/tracker/processes/uiprocess.py", line 228, in run
    self._ui_launcher.run_ui()
  File "/home/anon/kunquat/lib/python3.9/site-packages/kunquat/tracker/ui/uilauncher.py", line 135, in run_ui
    root_view = RootView()
  File "/home/anon/kunquat/lib/python3.9/site-packages/kunquat/tracker/ui/views/rootview.py", line 50, in __init__
    self._main_window = MainWindow()
  File "/home/anon/kunquat/lib/python3.9/site-packages/kunquat/tracker/ui/views/mainwindow.py", line 35, in __init__
    self._main_view = MainView()
  File "/home/anon/kunquat/lib/python3.9/site-packages/kunquat/tracker/ui/views/mainview.py", line 30, in __init__
    self._portal = Portal()
  File "/home/anon/kunquat/lib/python3.9/site-packages/kunquat/tracker/ui/views/portal.py", line 38, in __init__
    self._event_list_button = EventListButton()
  File "/home/anon/kunquat/lib/python3.9/site-packages/kunquat/tracker/ui/views/eventlistbutton.py", line 76, in __init__
    self._light = EventLight()
  File "/home/anon/kunquat/lib/python3.9/site-packages/kunquat/tracker/ui/views/eventlistbutton.py", line 41, in __init__
    self._refresh_timer.start(self._config['delta'] * 1000)
TypeError: arguments did not match any overloaded call:
  start(self, int): argument 1 has unexpected type 'float'
  start(self): too many arguments
```
