### ISSUE TITLE
Opening notation window crashes Kunquat on macOS

### ISSUE THREAD

**Issue by cyberixae** [kunquat/kunquat#718]
Traceback (most recent call last):
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/views/sheet/view.py", line 2065, in focusOutEvent
    self._sheet_manager.set_edit_mode(False)
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/model/sheetmanager.py", line 696, in set_edit_mode
    self._updater.signal_update('signal_edit_mode')
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/controller/updater.py", line 25, in signal_update
    assert not self._is_updating
AssertionError

**Comment by cyberixae** [comment]
After clicking "Exit Kunquat" the following error messages get printed to console

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/views/sheet/view.py", line 2055, in focusInEvent
    self._sheet_manager.set_edit_mode(True)
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/model/sheetmanager.py", line 696, in set_edit_mode
    self._updater.signal_update('signal_edit_mode')
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/controller/updater.py", line 25, in signal_update
    assert not self._is_updating
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/views/sheet/view.py", line 1558, in event
    return QWidget.event(self, event)
SystemError: <built-in function event> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtGui.QInputMethodQueryEvent'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/errordialog.py", line 100, in _show_dialog
    self.exec_()
SystemError: <built-in method exec_ of ErrorDialog object at 0x109ea1a68> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/errordialog.py", line 95, in _excepthook
    self.exceptionReceived.emit(details)
SystemError: <built-in method emit of PyQt5.QtCore.pyqtBoundSignal object at 0x11545e7d8> returned a result with an error set

Original exception was:
Traceback (most recent call last):
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/views/sheet/view.py", line 2065, in focusOutEvent
    self._sheet_manager.set_edit_mode(False)
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/model/sheetmanager.py", line 696, in set_edit_mode
    self._updater.signal_update('signal_edit_mode')
  File "/Users/cyberixae/kunquat/lib/python3.6/site-packages/kunquat/tracker/ui/controller/updater.py", line 25, in signal_update
    assert not self._is_updating
AssertionError
```
