### ISSUE TITLE
QImage, argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by rambit** [kunquat/kunquat#911]
I see you already fixed many issues in 944f75f9ce2471dd7822e408055f4b905c1a0296 but this seems to be another one. The width to QImage constructor seems to be a float when I open the example `Asturias.kqt` click on `Connections` and then `Edit` on `Guitar`. I think the issues started after upgrading to Python 3.8?

```
Traceback (most recent call last):
  File "/home/rambit/kunquat/lib/python3.8/site-packages/kunquat/tracker/ui/views/connections.py", line 219, in paintEvent
    self.viewport().paintEvent(event)
  File "/home/rambit/kunquat/lib/python3.8/site-packages/kunquat/tracker/ui/views/connections.py", line 789, in paintEvent
    cable.make_cable()
  File "/home/rambit/kunquat/lib/python3.8/site-packages/kunquat/tracker/ui/views/connectioncable.py", line 92, in make_cable
    self._image = QImage(width, height, QImage.Format_ARGB32_Premultiplied)
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(QSize, QImage.Format): argument 1 has unexpected type 'float'
  QImage(int, int, QImage.Format): argument 1 has unexpected type 'float'
  QImage(bytes, int, int, QImage.Format): argument 1 has unexpected type 'float'
  QImage(sip.voidptr, int, int, QImage.Format): argument 1 has unexpected type 'float'
  QImage(bytes, int, int, int, QImage.Format): argument 1 has unexpected type 'float'
  QImage(sip.voidptr, int, int, int, QImage.Format): argument 1 has unexpected type 'float'
  QImage(List[str]): argument 1 has unexpected type 'float'
  QImage(str, format: str = None): argument 1 has unexpected type 'float'
  QImage(QImage): argument 1 has unexpected type 'float'
  QImage(Any): too many arguments
```

**Comment by kagu** [comment]
Thanks for reporting these!
