### ISSUE TITLE
Can't compile: too many arguments for format

### ISSUE THREAD

**Issue by absolutelynothinghere** [kunquat/kunquat#915]
Hello, I just tried compiling Kunquat and it fails with errors, most commonly the "`too many arguments for format`" error. This persists in both the 0.9.4 release and the current GitHub code snapshot. Please see the attached log file:
[make.log](https://github.com/kunquat/kunquat/files/7605040/make.log)

Thank you 😊

**Comment by kagu** [comment]
Hi, could you try the version in the linked pull request and see if it works for you?

**Comment by absolutelynothinghere** [comment]
Still doesn't compile, but now it's a different error...

```
======================================================================
ERROR: kunquat.tracker.ui.model.test_tstamp (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: kunquat.tracker.ui.model.test_tstamp
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/anon/Downloads/kunquat-master/kunquat/tracker/ui/model/test_tstamp.py", line 18, in <module>
    from . import tstamp
  File "/home/anon/Downloads/kunquat-master/kunquat/tracker/ui/model/tstamp.py", line 14, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)


======================================================================
ERROR: kunquat.tracker.ui.views.sheet.test_utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: kunquat.tracker.ui.views.sheet.test_utils
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/anon/Downloads/kunquat-master/kunquat/tracker/ui/views/sheet/test_utils.py", line 19, in <module>
    import kunquat.tracker.ui.model.tstamp as tstamp
  File "/home/anon/Downloads/kunquat-master/kunquat/tracker/ui/model/tstamp.py", line 14, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)


----------------------------------------------------------------------
Ran 47 tests in 22.113s

FAILED (errors=2)
fabricate: 'env' exited with status 1
```
